$(document).ready(function(){
    $('#first').click(function(){
        $('#change').text("Children learn to understand the world and their place in it through play. It is where they’re free to act out their inner feelings and deepest emotions. Since the child cannot adequately express themselves in the adult world, the therapist joins the child in their world, on their level. As they play, the child may become less guarded and more apt to share their feelings. But they aren’t pressured. They’re allowed to do so in their own time and with their own method of communication. Play therapy will differ depending on the therapist and the particular needs of the child. To begin, the therapist may want to observe the child at play. They may also want to conduct separate interviews with the child, parents, or teachers. After a thorough assessment, the therapist will set some therapeutic goals, decide on what limits may be necessary, and formulate a plan for how to proceed. Much can be revealed in how a child interacts with different types of toys and how their behavior changes from session to session. They may use play to act out fears and anxieties, as a soothing mechanism, or to heal and problem-solve. Each child is different, so therapy will be tailored to their individual needs. As therapy progresses, behaviors and goals can be reassessed. It can help teach conflict resolution, promote healing, and improve family dynamics.");
    });

    $('#second').click( function(){
        $('#change').text("CBT is based on the concept that your thoughts, feelings, physical sensations and actions are interconnected, and that negative thoughts and feelings can trap you in a vicious cycle.CBT aims to help you deal with overwhelming problems in a more positive way by breaking them down into smaller parts.You're shown how to change these negative patterns to improve the way you feel.Unlike some other talking treatments, CBT deals with your current problems, rather than focusing on issues from your past.It looks for practical ways to improve your state of mind on a daily basis.If CBT is recommended, you'll usually have a session with a therapist once a week or once every 2 weeks. The course of treatment usually lasts for between 5 and 20 sessions, with each session lasting 30 to 60 minutes. During the sessions, you'll work with your therapist to break down your problems into their separate parts, such as your thoughts, physical feelings and actions. You and your therapist will analyse these areas to work out if they're unrealistic or unhelpful, and to determine the effect they have on each other and on you.Your therapist will then be able to help you work out how to change unhelpful thoughts and behaviours.");
    });

    $('#third').click( function(){
        $('#change').text("Psychiatrists use a variety of treatments – including various forms of psychotherapy, medications, psychosocial interventions and other treatments (such as electroconvulsive therapy or ECT), depending on the needs of each patient.Psychotherapy, sometimes called talk therapy, is a treatment that involves a talking relationship between a therapist and patient. It can be used to treat a broad variety of mental disorders and emotional difficulties. The goal of psychotherapy is to eliminate or control disabling or troubling symptoms so the patient can function better. Depending on the extent of the problem, treatment may take just a few sessions over a week or two or may take many sessions over a period of years. Psychotherapy can be done individually, as a couple, with a family, or in a group. There are many forms of psychotherapy. There are psychotherapies that help patients change behaviors or thought patterns, psychotherapies that help patients explore the effect of past relationships and experiences on present behaviors, and psychotherapies that are tailored to help solve other problems in specific ways. Cognitive behavior therapy is a goal-oriented therapy focusing on problem solving. Psychoanalysis is an intensive form of individual psychotherapy which requires frequent sessions over several years.");
    });

    $('#fourth').click( function(){
        $('#change').text("Clinical hypnosis an approach used by licensed and trained clinicians for treating a psychological or physical problem and involves a set of skills that facilitate a natural, altered state of consciousness called trance.  During therapeutic trance, the conscious, critical mind, is usually relaxed and relatively inactive, while the subconscious mind is able to access resources, skills, and abilities that are otherwise unavailable to the conscious mind. During trance, openness to suggestibility can be enhanced, senses heightened, mental absorption increased, and imagination activated in controlled manners that promote insight, ego strengthening, and activation of solution-focused skills. Hypnosis elicits and makes use of the experience of a highly relaxed state of inner absorption, concentration, and focused attention. Using hypnosis and self-hypnosis can allow people to have increased control over their behaviors, thoughts, emotional responses, and even physiological responses and physical health.  Because hypnosis allows people to use more of their potential, learning self-hypnosis is the ultimate act of self-control. ");
    });

    $('#fifth').click( function(){
        $('#change').text("Mindfulness-based cognitive therapy builds upon the principles of cognitive therapy by using techniques such as mindfulness meditation to teach people to consciously pay attention to their thoughts and feelings without placing any judgments upon them.There are a number of mindfulness techniques and exercises that are utilized as a part of MBCT. MBCT was developed by therapists Zindel Segal, Mark Williams, and John Teasdale, who sought to build upon cognitive therapy. They felt that by integrating cognitive therapy with a program developed in 1979 by Jon Kabat-Zinn called mindfulness-based stress reduction (MBSR), therapy could be more effective.");
    });

});


